### ISSUE TITLE
Usage of deprecated union operator

### ISSUE THREAD

**Issue by factuno-db** [google/jsinterop-generator#37]
Builds of elemental2 fail with Bazel 0.26.0 due to the usage of the deprecated "+" operator on depsets (see tracking issue https://github.com/bazelbuild/bazel/issues/5817):

```
ERROR: /(...)/external/com_google_elemental2/java/elemental2/core/BUILD:38:1: in _jsinterop_generator rule @com_google_elemental2//java/elemental2/core:core__internal_src_generated: 
Traceback (most recent call last):
        File "/(...)/external/com_google_elemental2/java/elemental2/core/BUILD", line 38
                _jsinterop_generator(name = 'core__internal_src_generated')
        File "/(...)/external/com_google_jsinterop_generator/jsinterop_generator.bzl", line 124, in _jsinterop_generator_impl
                _get_generator_files(ctx.attr.deps)
        File "/(...)/external/com_google_jsinterop_generator/jsinterop_generator.bzl", line 49, in _get_generator_files
                transitive_srcs += target_provider.transitive_sources
`+` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily disable this check.
```

**Comment by jDramaix** [comment]
Thanks! I have a cl in review internally that will fix this issue.

**Comment by jDramaix** [comment]
Need to rollback the cl
